### ISSUE TITLE
Dependency issue: No module named tenacity

### ISSUE THREAD

**Issue by kaotika** [noisyboiler/wampy#58]
I tried to install wampy in a clean python environment (docker python:latest). There is no difference between python 2 and 3.
```bash
pip install wampy
python -c "import wampy"
```
lead to this error:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/wampy/__init__.py", line 18, in <module>
    from wampy.peers.clients import Client  # noqa
  File "/usr/local/lib/python2.7/site-packages/wampy/peers/__init__.py", line 5, in <module>
    from . clients import Client  # noqa
  File "/usr/local/lib/python2.7/site-packages/wampy/peers/clients.py", line 18, in <module>
    from wampy.peers.routers import Router
  File "/usr/local/lib/python2.7/site-packages/wampy/peers/routers.py", line 13, in <module>
    from tenacity import retry, stop_after_attempt, wait_fixed
ImportError: No module named tenacity
```

Install tenacity seem to fix the issue:
```bash
pip install tenacity
python -c "import wampy"
```

**Comment by noisyboiler** [comment]
hmm. this was removed in master https://github.com/noisyboiler/wampy/pull/53
see: https://github.com/noisyboiler/wampy/pull/53/files#diff-0
but that's not been released - I'll do that.

So it looks like i'm not expecting you to install that way! :)
Because tenacity is a dev only req in `setup.py`. My bad.
I'll sort this out asap.

Many thanks for taking the time to let me know @kaotika

**Comment by noisyboiler** [comment]
thanks @kaotika
fixed with https://github.com/noisyboiler/wampy/releases/tag/0.9.14
